name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: acrhomeworktask.azurecr.io
  IMAGE_NAME: nextjsbasicapp
  KUBE_CONFIG_PATH: ~/.kube/config
  EXTERNAL_IP: ${{ secrets.EXTERNAL_IP }}

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Security Audit in Docker
      run: |
        docker build -t audit-image --target=builder .
        docker run audit-image npm audit --audit-level=moderate
      continue-on-error: true

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - run: |
       docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}

    - name: Azure CLI Logins
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Substitute variables in Ingress manifest
      run: |
        envsubst < k8s/ingress.yaml > k8s/ingress.yaml.out
        mv k8s/ingress.yaml.out k8s/ingress.yaml
      env:
        EXTERNAL_IP: ${{ env.EXTERNAL_IP }}
     
    - name: Substitute variables in Kubernetes manifests
      run: |
        envsubst < k8s/deployment.yaml > k8s/deployment.yaml.out
        mv k8s/deployment.yaml.out k8s/deployment.yaml
      env:
        IMAGE_TAG: ${{ github.sha }}

    - uses: azure/setup-kubectl@v3

    - uses: Azure/aks-set-context@v4
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group:  ${{ secrets.AZURE_RESOURCE_GROUP }}

    - uses: Azure/k8s-create-secret@v4
      with:
          container-registry-url: ${{ env.AZURE_CONTAINER_REGISTRY }}
          container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
          container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
          secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v6
      with:
         resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
         name:  ${{ secrets.AKS_CLUSTER_NAME }}
         action: deploy
         strategy: basic
         private-cluster: true
         
         manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
            k8s/
         images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}
         imagepullsecrets: |
            k8s-secret


 #   - name: Verify deployment
#      run: |
#       kubectl rollout status deployment/nextjs-basic-app-deployment 
 #       kubectl get pods 
#      env:
 #       KUBECONFIG: $KUBE_CONFIG_PATH
