name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: acrhomeworktask.azurecr.io
  IMAGE_NAME: nextjsbasicapp
  KUBE_CONFIG_PATH: ~/.kube/config
  EXTERNAL_IP: 20.54.216.148

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Run Security Audit in Docker
#      run: |
#        docker build -t audit-image --target=builder .
#        docker run audit-image npm audit --audit-level=moderate
#      continue-on-error: true

#    - name: 'Login to ACR'
#      uses: azure/docker-login@v1
#      with:
#        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
#        username: ${{ secrets.AZURE_CLIENT_ID }}
#        password: ${{ secrets.AZURE_CLIENT_SECRET }}
#    - run: |
#       docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}
#        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}

#    - name: Get AKS credentials
#      run: |
#        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --file $KUBE_CONFIG_PATH

    - name: Substitute variables in Ingress manifest
      run: |
        envsubst < k8s/ingress.yaml > k8s/ingress.yaml.out
        mv k8s/ingress.yaml.out k8s/ingress.yaml
      env:
        EXTERNAL_IP: ${{ env.EXTERNAL_IP }}

        
    - name: Substitute variables in Kubernetes manifests
      run: |
        envsubst < k8s/deployment.yaml > k8s/deployment.yaml.out
        mv k8s/deployment.yaml.out k8s/deployment.yaml
        IMAGE_TAG: test

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
      env:
        KUBECONFIG: $KUBE_CONFIG_PATH
        
 #   - name: Deploy to AKS
#      run: |
 #       kubectl apply -f k8s/deployment.yaml
#        kubectl apply -f k8s/service.yaml
#        kubectl apply -f k8s/ingress.yaml
#      env:
#        KUBECONFIG: $KUBE_CONFIG_PATH

 #   - name: Verify deployment
#      run: |
#       kubectl rollout status deployment/nextjs-basic-app-deployment 
 #       kubectl get pods 
#      env:
 #       KUBECONFIG: $KUBE_CONFIG_PATH
