name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: acrhomeworktask.azurecr.io
  IMAGE_NAME: nextjsbasicapp
  KUBE_CONFIG_PATH: ~/.kube/config
  EXTERNAL_IP: ${{ secrets.EXTERNAL_IP }}

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Run Security Audit in Docker
#      run: |
#        docker build -t audit-image --target=builder .
#        docker run audit-image npm audit --audit-level=moderate
#      continue-on-error: true

#    - name: 'Login to ACR'
#      uses: azure/docker-login@v1
#      with:
#        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
#        username: ${{ secrets.AZURE_CLIENT_ID }}
#        password: ${{ secrets.AZURE_CLIENT_SECRET }}
#    - run: |
#       docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}
#        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/nextjs:${{ github.sha }}

    - name: Azure CLI Logins
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Substitute variables in Ingress manifest
      run: |
        envsubst < k8s/ingress.yaml > k8s/ingress.yaml.out
        mv k8s/ingress.yaml.out k8s/ingress.yaml
      env:
        EXTERNAL_IP: ${{ env.EXTERNAL_IP }}

        
    - name: Substitute variables in Kubernetes manifests
      run: |
        envsubst < k8s/deployment.yaml > k8s/deployment.yaml.out
        mv k8s/deployment.yaml.out k8s/deployment.yaml
      env:
        IMAGE_TAG: ${{ github.sha }}

    - name: Print KUBECONFIG
      run: cat ~/.kube/config

    - name: Test kubectl connectivity
      run: kubectl get nodes

    - name: Deploy to AKS
      run: |
        export KUBECONFIG=$KUBE_CONFIG_PATH
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false
        kubectl apply -f k8s/ingress.yaml --validate=false
      env:
        KUBECONFIG: $KUBE_CONFIG_PATH
        

 #   - name: Verify deployment
#      run: |
#       kubectl rollout status deployment/nextjs-basic-app-deployment 
 #       kubectl get pods 
#      env:
 #       KUBECONFIG: $KUBE_CONFIG_PATH
